DELETE http://localhost:3001/api/blogs/66c1d85b27acced01d1afb44
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFydHR1MDMiLCJpZCI6IjY2YzFkNDUxN2U1ZmI2ZDcyZjczN2UzYiIsImlhdCI6MTcyMzk3ODg2NH0.cOYDgVLF8j9vacjv6OKjKi9wblao8_UCUQzesaoneyM
