POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFydHR1MDMiLCJpZCI6IjY2Yzg5ZmEzNzRiYWJmZjMwNzk2YWE5MiIsImlhdCI6MTcyNDQyNDEyOH0.EuGnTGwgjEo_JLKtZfylt-J5YiNmMSZ-iq-QDXfY-DY


{
  "title": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfL",
  "author": "afiuhfaftyuiopsafoiuhyfaff",
  "url": "ajfoiajfo32441iaf.cosfsasfsahfum"
}